/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 syrus.gltf --transform 
Files: syrus.gltf [43.34MB] > C:\Users\Gautam\Desktop\Syrus_2024\public\Spiderman\Syrus3D\Syrus3D\syrus-transformed.glb [1.46MB] (97%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Spiderman/Syrus3D/Syrus3D/syrus-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_403.geometry} material={materials.S_U_I_T} scale={0.01} />
      <mesh geometry={nodes.Object_404.geometry} material={materials.M_A_S_K} scale={0.01} />
      <mesh geometry={nodes.Object_405.geometry} material={materials.E_Y_E_S} scale={0.01} />
      <mesh geometry={nodes.BezierCurve_Auto_03_0.geometry} material={materials.Auto_03} position={[0.148, 1.008, 0.553]} rotation={[-Math.PI / 2, 0, -3.131]} scale={0.198} />
      <mesh geometry={nodes.Cube_Auto_04_0.geometry} material={materials.Auto_04} position={[-0.001, 1.146, 0.432]} rotation={[-1.199, 0.004, 1.58]} scale={0.198} />
      <mesh geometry={nodes.Cube_Screen_0.geometry} material={materials.Screen} position={[-0.001, 1.146, 0.432]} rotation={[-1.199, 0.004, 1.58]} scale={0.198} />
      <mesh geometry={nodes.Cube004_Auto_01_0.geometry} material={materials.Auto_01} position={[-0.002, 0.996, 0.4]} rotation={[-Math.PI / 2, 0, -3.131]} scale={0.198} />
      <mesh geometry={nodes.Cube012_Auto_02_0.geometry} material={materials.Auto_02} position={[0.178, 0.996, 0.368]} rotation={[-Math.PI / 2, 0, -3.131]} scale={0.198} />
    </group>
  )
}

useGLTF.preload('/syrus-transformed.glb')
